// <auto-generated />
namespace Secretary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trytoupdatewithoutUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trytoupdatewithoutUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611302042218_try to update without UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
